[package]
name = "pomodoro-druid"
version = "0.1.0"
authors = ["Mikhail Topolskiy <mikhail.topolskiy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
druid = "0.5.0"
rodio="0.11.0"